### ISSUE TITLE
Does this work with SD 1.5?

### ISSUE THREAD

**Issue by cliffrowley** [asagi4/comfyui-prompt-control#14]
I loaded up the example workflow and tried it with a SD 1.5 checkpoint, but it throws an error from `prepareXL`. Is this an XL only node? (I didn't see anything in the docs that says so, but I could have easily missed it!)

**Comment by asagi4** [comment]
I just happened to push a fix for this issue a few moments ago.

ComfyUI has changed its token datastructure and that caused the extension to detect SD 1.5 as SDXL if you had the advanced clip extension installed. If you update your extension it should work.

Though be warned, there were some sampling changes to ComfyUI yesterday and today that might have also broken things; My ComfyUI is currently at commit c837a173fab41b7132a72ab01b256b714bd6adb2 because the changes break AITemplate, and I very much like the speedup AIT gives me.

**Comment by cliffrowley** [comment]
Wonderful, thank you so much!

**Comment by asagi4** [comment]
I fixed AIT for recent ComfyUI and things seem to work normally, so I'm closing this issue.

**Comment by cliffrowley** [comment]
All works just fine here, thank you for your efforts!
