### ISSUE TITLE
Some parts of Scheduling syntax are not understood.

### ISSUE THREAD

**Issue by ytoaa** [asagi4/comfyui-prompt-control#55]
![image](https://github.com/user-attachments/assets/293da832-05c6-4324-883d-aeb854ec8819)
![image](https://github.com/user-attachments/assets/230c09f1-80f8-4c78-9f61-83a7d3d3d04d)
I think 0.8 means 80%, so I have to stop Laura after proceeding to step 16, which is 80% from step 20, but I only apply it to step 5, and stop Laura.

After a few attempts I found out this was responding to cfg...

**Comment by asagi4** [comment]
Hm. Can I get a workflow to debug this?

**Comment by ytoaa** [comment]
![workflow (3)](https://github.com/user-attachments/assets/6709c673-68a7-4b79-b8f0-dd46b9e699c1)

**Comment by asagi4** [comment]
The PC override of the LoRA offload device on OOM happens regardless of ComfyUI options if you haven't disabled it, but without `--highvram` or `--gpu-only` the offload device may already be the CPU, in which case the behaviour simply doesn't change.

**Comment by asagi4** [comment]
Anyway, the latest commit should fix this issue. It was a problem with detecting custom samplers (required because the function prototypes are different) that seems to trigger whenever there are other monkeypatches, and since the  Inspire sampler uses the custom sampling function from ComfyUI, it mixed up CFG and steps

**Comment by ytoaa** [comment]
> Anyway, the latest commit should fix this issue. It was a problem with detecting custom samplers (required because the function prototypes are different) that seems to trigger whenever there are other monkeypatches, and since the Inspire sampler uses the custom sampling function from ComfyUI, it mixed up CFG and steps

[INFO] PromptControl: SamplerCustom detected, number of steps not available. LoRA schedules will be calculated based on the number of sigmas (11)

When I try with ksampler (inspire), I get the following phrase on the console, what do you mean?
It doesn't come out of the usual ksampler.

**Comment by asagi4** [comment]
@ytoaa it just means that instead of the step count to calculate the point at which LoRAs change, the number of sigmas are used. For some samplers, the number of sigmas doesn't always match the number of configured steps. You'll note it says (11) there, meaning the calculation is done with 11 steps instead of 10.

The step count isn't available to the custom sampler function I hook into, which Inspire uses, so I have to use the sigmas instead.
