### ISSUE TITLE
[BUG] Alternating prompt syntax generates grey

### ISSUE THREAD

**Issue by jordanjay29** [asagi4/comfyui-prompt-control#82]
**Before you start**
Verify the following:
1. Yes
2. Yes
3. Not in known issues

**Describe the bug**
[alternating|prompt] syntax appears to generate noise instead of an image, regular [scheduled:prompt:0.1] seems to be working as intended.

Unsure if this is related to #78, I'm unfamiliar on how to add the debug flag to comfyui but will run again with it once I learn how. 

**To Reproduce**
Run a basic prompt control workflow with PC Schedule Prompt (or Advanced of the same) in place of ClipTextEncoder.
Use an [alternating|prompt] syntax in prompt. 
Generate
Outcome produces a grey box

**Expected behavior**
Expected the image to generate clean from noise, and for the prompt to respect the [alternating|prompt] sequence.

**Comment by asagi4** [comment]
It seems that the alternating syntax produces a conditioning that applies nowhere, giving you grey.

I'm not sure what's going wrong because looking at the conds produced in a minimal workflow that just does a debug print, the timestepping appears correct at first glance.

I'm currently away from my desktop (only remote access via phone available) so it'll probably be until next week before I'm able to properly debug and fix this.

**Comment by asagi4** [comment]
I got home a bit earlier than predicted; it wasn't too difficult to figure out. Turns out my attempt at optimizing things probably broke this.

It seems to work for me now, but please test before I close this just in case I missed something

**Comment by jordanjay29** [comment]
Didn't get time to test until now, can confirm it does work. Thanks!
