### ISSUE TITLE
[FR] new node Automatic Prompt

### ISSUE THREAD

**Issue by morozig** [asagi4/comfyui-prompt-control#85]
I would really like to add a new node called "Automatic Prompt" with textarea to write your prompt. It allows inserting LoRAs with their trigger words into prompt as well as incapsulates main promt control logic inside.
![automatic-prompt](https://github.com/user-attachments/assets/c47016ca-526c-4216-9bfc-821f51f51f2b)
It should have a single input `clip` and a single output `conditioning` so that it can be inserted in a basic workflow in place of positive prompt(and negative if needed):
![workflow](https://github.com/user-attachments/assets/f3e4d208-00a1-433f-b427-aa9581b30dce)
It should incapsulate `PCLazyTextEncode` and `PCLazyLoraLoader`. I've seen your `example-lazy` workflow and I don't get why `PCLazyLoraLoader` needs `model` input when resulting graph with clip hooks does not use it at all.
But the most important feature to have (and hardest to implement) is a text field at the bottom labeled "Add LoRA". It would be a search textbox allowing you to choose one lora in a dropdown list with filtering option. This filtering option is crucial as I have so many LoRAs in different folders that it's impossible to scroll a whole list but typing `flux/` narrows it down. Apon selecting a LoRA it would be inserted at the end of prompt textarea with its triggerwords, just like Automatic1111 do(hence the name) and textbox is cleared allowing to add next LoRA. Default `Load LoRA` node from `Comfy-Core` has a perfect lora select textbox. Oh, and this textbox should not be a node input, because you can add many different LoRAs with it.
![image](https://github.com/user-attachments/assets/3428898f-7744-4cf7-8138-c040a2fa9d25)
As a super cool bonus would be a button to the right of "Add LoRA" textbox that would open a modal window with filterable grid of LoRA previews(when they have png preview or blanc square with file name instead).
This node would be totally optional not breaking any existing workflows and can be dropped in favor of existing nodes for more complex scenarios.
So, do you get what I want and is it possible to do? I could probably help with JS part if needed. I feel like this autofill textbox would be hard to implement, as I don't remember seeing such things in comfy repos. And the modal window is pure luxury, probably not that important.

**Comment by asagi4** [comment]
I think this goes a fair bit beyond the scope of my nodes. Having a drop-down for LoRA selection kind of goes against the whole idea of using the prompt to control things.

For the LoRA trigger words, I'm not even sure how to determine what they are, since trigger words aren't a thing as far as the LoRA model is concerned; they're just what people call captions that appear in all (or most) of the dataset, as far as I know.

However, you can use https://github.com/pythongosssss/ComfyUI-Custom-Scripts to get autocompletion for the <lora:... syntax. It works fine and I think it would fit your usecase.

The reason PCLazyLoraLoader takes a model input is that when you load a non-scheduled LoRA, it just generates a standard LoRALoader. Currently, it significantly reduces latency in cases where you don't have scheduled LoRAs since hooks always get unloaded after sampling even when that's not necessary (ie. when the next prompt would just apply them again)

I'm planning on having some convenience nodes at some point, but I'm not sure yet what the design should be.

**Comment by morozig** [comment]
> I think this goes a fair bit beyond the scope of my nodes. Having a drop-down for LoRA selection kind of goes against the whole idea of using the prompt to control things.
> 
> For the LoRA trigger words, I'm not even sure how to determine what they are, since trigger words aren't a thing as far as the LoRA model is concerned; they're just what people call captions that appear in all (or most) of the dataset, as far as I know.
> 
> However, you can use https://github.com/pythongosssss/ComfyUI-Custom-Scripts to get autocompletion for the <lora:... syntax. It works fine and I think it would fit your usecase.
> 
> The reason PCLazyLoraLoader takes a model input is that when you load a non-scheduled LoRA, it just generates a standard LoRALoader. Currently, it significantly reduces latency in cases where you don't have scheduled LoRAs since hooks always get unloaded after sampling even when that's not necessary (ie. when the next prompt would just apply them again)
> 
> I'm planning on having some convenience nodes at some point, but I'm not sure yet what the design should be.

I see. Thanks for your reply! I think here the most important thing is how you use comfy yourself, I've described how I use it constantly and what I want to improve, I didn't know about pythongosssss autocomplete, thanks for mentioning it, but it does not add trigger words eather. Those are the words saved in a json file under `activation words` when downloaded from civitai and placed near .safetensors file, for example `in the style of cksc`. LoRA author specifies them when publishing LoRA on civitai and Automatic1111 adds them to prompt when LoRA is selected. Also adding LoRA to the prompt with pythongosssss is meaningless without some prompt control mechanism.
I get it that LoraLoader saves a lot of time but it is a tradeoff for simplicity and readability of a graph, new users would instantly understand how to use a node that is identical to default text encode, and experienced users could do all optimisations manually.
Now, if I ever would do this node myself as I've described it here, would you accept a pull request or is it goes against your vision for this repo? In that case let's just close this issue and I'll have to do some kind of fork and publish it with just this node and a reference to your repo. But I'll mention that while your repo is called "prompt control" it was inspired by Automatic1111 which I like and use a lot and I just wanted to make something similar.

**Comment by asagi4** [comment]
Automatically adding trigger words could be in scope but I don't use any kind of auto-activation-word feature myself (I don't have those json files you speak of) and I don't think just mentioning a LoRA should automatically add anything to the prompt, so if I did add that feature, there would have to be a separate trigger for it.

I don't think I want to include nodes that require front-end code, so that seems best left to another project. I also don't think having LazyLoRALoader and LazyTextEncode as separate nodes complicates matters too much (though as I said, I'm planning on having an all-in-one node at some point), and the performance benefit of avoiding hooks when they're not needed is quite significant. On my system, it easily saves over a second of gen time, which is too much to just not have there by default. If the performance optimization ever becomes unnecessary, I'll just add a PCTextEncodeV2 with a simpler interface and offer that as the default.

**Comment by morozig** [comment]
Yeah, in that case there is no reason to do it in this repo.

**Comment by morozig** [comment]
Made a quick [fork](https://github.com/morozig/comfyui-automatic-prompt) with this component
